const enc = new TextEncoder();
const b64u = bytes => btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64u = text => Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/') + '='.repeat((4-text.length%4)%4)), c=>c.charCodeAt(0));
const equal=(a,b)=>{if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0};
async function hmac(secret,text){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text)))}
export async function verifyPassword(password, encoded){try{const [kind,roundsText,saltText,wantText]=encoded.split('$');const rounds=Number(roundsText);if(kind!=='pbkdf2-sha256'||!Number.isInteger(rounds)||rounds<100000||rounds>2000000)return false;const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const got=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unb64u(saltText),iterations:rounds},key,256));return equal(got,unb64u(wantText))}catch{return false}}
export async function makeSession(secret,now=Date.now(),sid=crypto.randomUUID()){const payload=b64u(enc.encode(JSON.stringify({sid,exp:Math.floor(now/1000)+60*60*24*30})));return `${payload}.${b64u(await hmac(secret,payload))}`}
export async function readSession(token,secret,now=Date.now()){try{const [payload,sig]=token.split('.');if(!payload||!sig||!equal(await hmac(secret,payload),unb64u(sig)))return null;const value=JSON.parse(new TextDecoder().decode(unb64u(payload)));return typeof value.sid==='string'&&value.sid&&value.exp>Math.floor(now/1000)?value:null}catch{return null}}
export async function verifySession(token,secret,now=Date.now()){return !!(await readSession(token,secret,now))}
export function cookie(request,name){const match=request.headers.get('Cookie')?.match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));return match?decodeURIComponent(match[1]):''}
